payment service implemented
cyneptic/letsgo pull request #6
Opened 2023-06-23 14:57 UTC by ali-mahdavi-mehr

2023-06-25 15:00 UTC, cyneptic requested changes
It appears you have changed the reservation.go and reservation struct
develop branch already has the changed reservation struct that you requested, you must pull that and redo some of your work as you must not make any changes to reservation.go or reservation struct.

2023-06-25 15:00 UTC, cyneptic commented on cmd/main.go
> +	uuid.Parse("4324902342384")
It's unclear what this is for, please follow clean code principles.

2023-06-25 15:00 UTC, cyneptic commented on cmd/main.go
> +	srvPayment := service.NewPaymentService(redisDb, gormDb)
in order to have a clean main.go it has been decided to make the service and repository within the handler creation function.

2023-06-25 15:00 UTC, cyneptic commented on controller/payment_handler.go
> +	e.POST("/verify-payment", handler.VerifyPayment)
if possible try using lowercase names without hyphens for endpoints to be consistent with rest of the project.

2023-06-25 15:00 UTC, cyneptic commented on controller/payment_handler.go
> +	id := "4324902342384"
it appears this was a temporary solution to test the code but you forgot to uncomment the line above and replace this.

2023-06-25 15:00 UTC, cyneptic commented on controller/payment_handler.go
> +	id := "4324902342384"
it appears this was a temporary solution to test the code but you forgot to uncomment the line above and replace this.

2023-06-26 14:25 UTC, cyneptic requested changes

2023-06-26 14:25 UTC, cyneptic commented on controller/payment_handler.go
> +	}
validations should be in a controller/validators/ folder in a relative *_validator.go

2023-06-26 14:25 UTC, cyneptic commented on controller/payment_handler.go
> +	reservationId := e.FormValue("SaleOrderId")
we need validations for all parameters, client might not use what we expect.
validations should be in a controller/validators/ folder in a relative *_validator.go

2023-06-26 14:25 UTC, cyneptic commented on internal/core/service/payment_service.go
> +
communicating with an outside program should only be done via the infrastructure section using a port contract.
you cannot contact (send a request in this case) to outside directly from the core.
this conflicts with hexagonal architecture.

2023-06-26 14:25 UTC, cyneptic commented on internal/core/service/payment_service.go
> +
communicating with an outside program should only be done via the infrastructure section using a port contract.
you cannot contact (send a request in this case) to outside directly from the core.
this conflicts with hexagonal architecture.

2023-06-26 14:25 UTC, cyneptic commented on internal/core/service/payment_utils.go
when moving the request to infrastructure you might need to move this utils file or parts of it to infrastructure aswell.

2023-06-27 08:27 UTC, ali-mahdavi-mehr commented on cmd/main.go
> +	uuid.Parse("4324902342384")
it's just for testing,i forgot to delete it

2023-06-29 14:48 UTC, cyneptic requested changes
please pull development branch and make sure there are no merge conflicts.

2023-06-29 14:48 UTC, cyneptic commented on cmd/main.go
> +	srvPayment := service.NewPaymentService(redisDb, gormDb, paymentGateway)
db, redis and provider creation should be done inside NewPaymentService() function.
and service should be made inside NewPaymentHandler() function.

this cleans up the main file and separates concerns giving the responsibility of making the dependencies of each to their constructor function.

2023-06-29 15:16 UTC, cyneptic requested changes

2023-06-29 15:16 UTC, cyneptic commented on internal/core/service/payment_service.go
> +		`, refID)
if possbile move this to provider, because it conflicts with separation of concern principle and if we were to change provider in the future we have to do changes in the service aswell.

2023-06-29 19:09 UTC, cyneptic commented
LGTM! Thanks.

2023-06-29 19:09 UTC, merged